linters-settings:
  gocognit:
    min-complexity: 25
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - errname
    - exhaustive
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - revive
    - staticcheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  max-same-issues: 10
  exclude-rules:
    - path: _test\.go
      linters:
        - bodyclose
        - gosec
        - noctx
        - unparam